import os

urls_filename = os.path.join(f'{os.getcwd()}/app/files/all_files/' , 'urls.txt')
app_version_filename = os.path.join(f'{os.getcwd()}/app/files/all_files/' , 'app_version.txt')
url_current_pos_filename = os.path.join(f'{os.getcwd()}/app/files/all_files/' , 'url_current_pos.txt')
delay_per_update_filename = os.path.join(f'{os.getcwd()}/app/files/all_files/' , 'delay_per_update.txt')
total_updates_filename = os.path.join(f'{os.getcwd()}/app/files/all_files/' , 'total_updates.txt')
total_errors_filename = os.path.join(f'{os.getcwd()}/app/files/all_files/' , 'total_errors.txt')
number_of_removed_machines_filename = os.path.join(f'{os.getcwd()}/app/files/all_files/' , 'number_of_removed_machines.txt')
number_of_inserted_machines_filename = os.path.join(f'{os.getcwd()}/app/files/all_files/' , 'number_of_inserted_machines.txt')
updates_per_machine_filename = os.path.join(f'{os.getcwd()}/app/files/all_files/' , 'updates_per_machine.txt')
number_of_github_updates_filename = os.path.join(f'{os.getcwd()}/app/files/all_files/' , 'number_of_github_updates.txt')
internet_error_datetime_filename = os.path.join(f'{os.getcwd()}/app/files/all_files/' , 'internet_error_datetime.txt')
#errors_occurred_15_filename = os.path.join(f'{os.getcwd()}/app/files/all_files/' , 'errors_occurred_15.txt')
progress_number_filename = os.path.join(f'{os.getcwd()}/app/files/all_files/' , 'progress_number.txt')
start_time_filename = os.path.join(f'{os.getcwd()}/app/files/all_files/' , 'start_time.txt')
end_time_filename = os.path.join(f'{os.getcwd()}/app/files/all_files/' , 'end_time.txt')
read_email_dates_filename = os.path.join(f'{os.getcwd()}/app/files/all_files/' , 'read_email_dates.txt')
app_started_filename = os.path.join(f'{os.getcwd()}/app/files/all_files/' , 'app_started.txt')
app_ended_filename = os.path.join(f'{os.getcwd()}/app/files/all_files/' , 'app_ended.txt')
number_of_captcha_challenges_filename = os.path.join(f'{os.getcwd()}/app/files/all_files/' , 'number_of_captcha_challenges.txt')
check_email_every_20_minutes_filename = os.path.join(f'{os.getcwd()}/app/files/all_files/' , 'check_email_every_20_minutes.txt')
daily_report_sent_filename = os.path.join(f'{os.getcwd()}/app/files/all_files/' , 'daily_report_sent.txt')
env_filename = os.path.join(f'{os.getcwd()}/app/' , '.env')